version: '3.9'
services:
  atom-report-management:
    container_name: atom-report-management
    stdin_open: true
    tty: true
    build: .
    ports:
      - '9007:9007'
    volumes:
      - ${PWD}/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
